[general]
live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
# ref - https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
TERM = "xterm-256color"

[font.bold]
style = "Light"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Light Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "ExtraLight"

# ref - https://github.com/alacritty/alacritty/blob/master/alacritty.yml
[window]
decorations = "none"
opacity = 0.95
startup_mode = "Maximized"
